version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
      - "444:443"
    links:
      - mysql
    networks:
      - sail
    # environment:
    #   WORDPRESS_DB_HOST: mysql
    #   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    #   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    #   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    # # volumes:
    # #   - wordpress:/var/www/html

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - sail
    ports:
      - "3308:3306"
  # portainer:
  #   image: portainer/portainer-ee:latest
  #   restart: always
  #   ports:
  #     - ${PORTAINER_PORT}:9000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
networks:
    sail:
        driver: bridge
# volumes:
#   wordpress:
#   mysql:
#   portainer_data:
